name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  # Allows manual triggering
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://ShreyasVavley:$HF_TOKEN@huggingface.co/spaces/ShreyasVavley/facial-emotion-console
          git push --force hf main
